name: flutter_app
description: This flutter app aims to allow study nurses to write stuff into the database.

# There is no intention to publish this package to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  http: ^1.3.0
  provider: ^6.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.16
  # no need to add the convert package as it is already included in the dart:core library

flutter:
  uses-material-design: true
  assets:
    - assets/
